### ISSUE TITLE
SunRadar

### ISSUE THREAD

**Issue by phoenixDownunder** [lakiryt/sunradar#1]
Works well, except I have tried to use it in 2 geographically separate locations in Australia
and the TimeZone does not change.
Melbourne (Covid Capital of Australia!) is GMT+10 and is correct
Adelaide South Australia is GMT + 9.5 !! (Pain in the neck I know but that's real)
Kind regards,
Bruce. bruce@toorak.com

![Screen Shot 2020-09-06 at 5 54 21 pm](https://user-images.githubusercontent.com/646180/92321070-47cc6a80-f06a-11ea-96e1-5bc0de1c593a.png)

**Comment by lakiryt** [comment]
Thank you for your report, Bruce!
I've updated the code to account for non-integer time zones.

Please note that the time zone does not (& is not meant to) change based on the coordinates, but based on the preference on your computer
(i.e. the sunset/sunrise times are displayed in the time zone you are in, rather than in local time; the "Timezone: " part clarifies how you should read the times but is basically just the time zone you have set on your device).

![スクリーンショット 2020-09-06 21 49 59](https://user-images.githubusercontent.com/13591027/92325691-e21db580-f04c-11ea-832e-b24e6ea44d7f.png)

**Comment by phoenixDownunder** [comment]
Thanks. Will experiment!
I like the application.
Kind Regards,
Bruce.
